import{a as p,S as w,i as g}from"./assets/vendor-30VqbI-A.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();p.defaults.baseURL="https://pixabay.com/api/";const d={key:"49370503-7e4a3b73ee503433174e66c4b",image_type:"photo",orientation:"horizontal",per_page:15,safesearch:!0};async function m(s,t){d.q=s,d.page=t;try{return(await p.get(`?${new URLSearchParams(d)}`)).data}catch(o){return o}}const y=document.querySelector(".gallery"),S=new w(".gallery li a",{captionsData:"alt",captionDelay:250});function f(s){const t=s.map(o=>{const{webformatURL:c,tags:e,largeImageURL:r,likes:n,views:h,comments:b,downloads:L}=o;return`<li class="gallery-card">
      <a href="${r}">
        <img src="${c}" alt="${e}" class="card-image" width="360" height="152" />
        <ul class="card-caption">
          <li class="image-tag"><p>Likes<br />${n}</p></li>
          <li class="image-tag"><p>Views<br />${h}</p></li>
          <li class="image-tag"><p>Comments<br />${b}</p></li>
          <li class="image-tag"><p>Downloads<br />${L}</p></li>
        </ul>
      </a>
    </li>`}).join("");y.insertAdjacentHTML("beforeend",t)}const P=document.querySelector(".form"),i=document.querySelector("button[type='button']"),a=document.querySelector(".loader");let u="",l=1;i.style="display: none";a.classList.toggle("loader");P.addEventListener("submit",q);i.addEventListener("click",v);async function q(s){if(s.preventDefault(),u=s.currentTarget.elements.search.value.trim(),l=1,!u){g.error({message:"Search field must not be empty!",position:"topRight"});return}y.innerHTML="",a.classList.toggle("loader");try{const t=await m(u,l);if(t.totalHits===0){g.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i.style="display: none";return}if(f(t.hits),t.totalHits<15){i.style="display: none";return}i.style="display: initial"}catch{a.innerHTML="Oops... something went wrong"}finally{a.classList.toggle("loader"),S.refresh()}}async function v(){l+=1,a.classList.toggle("loader");const t=document.querySelector(".gallery>li").getBoundingClientRect().height;try{const o=await m(u,l);o.totalHits>15*l?(f(o.hits),window.scrollBy({top:t*2,behavior:"smooth"})):(i.style="display: none",g.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{a.innerHTML="Oops... something went wrong"}finally{a.classList.toggle("loader")}}
//# sourceMappingURL=index.js.map
