import{a as p,S as w,i as u}from"./assets/vendor-30VqbI-A.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();p.defaults.baseURL="https://pixabay.com/api/";const d={key:"49370503-7e4a3b73ee503433174e66c4b",image_type:"photo",orientation:"horizontal",per_page:15,safesearch:!0};async function m(a,r){d.q=a,d.page=r;try{return await p.get(`?${new URLSearchParams(d)}`)}catch(s){return s}}const h=document.querySelector(".gallery"),o=document.querySelector(".loader"),S=new w(".gallery li a",{captionsData:"alt",captionDelay:250});function f(a){const r=a.map(s=>{const{webformatURL:n,tags:e,largeImageURL:t,likes:i,views:y,comments:L,downloads:b}=s;return`<li class="gallery-card">
        <a href="${t}">
          <img src="${n}" alt="${e}" class="card-image" width="360" height="152" />
          <ul class="card-caption">
            <li class="image-tag"><p>Likes<br />${i}</p></li>
            <li class="image-tag"><p>Views<br />${y}</p></li>
            <li class="image-tag"><p>Comments<br />${L}</p></li>
            <li class="image-tag"><p>Downloads<br />${b}</p></li>
          </ul>
        </a>
      </li>`}).join("");o.classList.toggle("loader"),h.insertAdjacentHTML("beforeend",r),S.refresh()}const P=document.querySelector(".form"),l=document.querySelector("button[type='button']");let c="",g=1;l.style="display: none";o.classList.toggle("loader");P.addEventListener("submit",q);l.addEventListener("click",v);function q(a){if(a.preventDefault(),c=a.currentTarget.elements.search.value.trim(),!c){u.error({message:"Search field must not be empty!",position:"topRight"});return}h.innerHTML="",o.classList.toggle("loader"),m(c,g).then(r=>{if(r.data.totalHits===0){o.classList.toggle("loader"),u.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l.style="display: none";return}f(r.data.hits),l.style="display: initial"}).catch(()=>{o.classList.toggle("loader"),o.innerHTML="Oops... something went wrong"})}function v(){g+=1,o.classList.toggle("loader");const r=document.querySelector(".gallery>li").getBoundingClientRect().height;m(c,g).then(s=>{if(s.data.totalHits<g*15){l.style="display: none",u.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),o.classList.toggle("loader");return}f(s.data.hits),window.scrollBy({top:r*2,behavior:"smooth"})}).catch(()=>{o.classList.toggle("loader"),o.innerHTML="Oops... something went wrong"})}
//# sourceMappingURL=index.js.map
